eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
server:
  port: 7004
spring:
  application:
    name: ribbon-consumer
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
    static-path-pattern: /static/**