eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
server:
  port: 7002
spring:
  application:
    name: ribbon-provider
  jpa:
    properties: org.hibernate.dialect.MySQL5Dialect
    database: MYSQL
    show-sql: true
  datasource:
    dbcp2:
      max-idle: 10
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5
    url: jdbc:mysql://192.168.154.128:3306/sunflower?setUnicode=true&characterEncoding=utf8
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mapping/*.xml
  type-aliases-package: com.cloud.ribbon.mapper
